const DEFAULTS={targetSize:38,targetSpeed:1,duration:60,sensitivity:1,screenShake:true,crosshairColor:'#f4f1ea',crosshairSize:12,crosshairThickness:2,crosshairGap:5,crosshairOpacity:100,centerDot:false};
const MODES={flick:{name:'Flick Standard',duration:60,goal:30,type:'static'},tracking:{name:'Flow Tracking',duration:45,goal:45,type:'moving'},reaction:{name:'Reaction Test',duration:30,goal:10,type:'reaction'},switch:{name:'Target Switch',duration:60,goal:60,type:'switch'},precision:{name:'Precision',duration:60,goal:25,type:'precision'}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let settings={...DEFAULTS,...JSON.parse(localStorage.getItem('strafe-settings')||'{}')};let records=JSON.parse(localStorage.getItem('strafe-records')||'{}');let currentMode='flick',game=null,raf=0;
const saveSettings=()=>localStorage.setItem('strafe-settings',JSON.stringify(settings));const saveRecords=()=>localStorage.setItem('strafe-records',JSON.stringify(records));
function showScreen(name){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===name+'Screen'));window.scrollTo(0,0);if(name==='home')updateHome();if(name==='stats')updateStats();}
$$('[data-screen]').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));
$$('[data-mode]').forEach(b=>b.onclick=()=>startGame(b.dataset.mode));$$('[data-quick-mode]').forEach(b=>b.onclick=()=>startGame(b.dataset.quickMode));
$('#fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();
function bindRange(id,format){const el=$('#'+id),out=$('#'+id+'Out');el.value=settings[id];out.textContent=format(el.value);el.oninput=()=>{settings[id]=id==='duration'||id==='targetSize'||id.startsWith('crosshair')?Number(el.value):id==='screenShake'?el.checked:Number(el.value);out.textContent=format(el.value);saveSettings();applyCrosshair()};}
bindRange('targetSize',v=>v);bindRange('targetSpeed',v=>Number(v).toFixed(1)+'×');bindRange('duration',v=>v+' sec');bindRange('sensitivity',v=>Number(v).toFixed(2));bindRange('crosshairSize',v=>v+' px');bindRange('crosshairThickness',v=>v+' px');bindRange('crosshairGap',v=>v+' px');bindRange('crosshairOpacity',v=>v+'%');
$('#screenShake').checked=settings.screenShake;$('#screenShake').onchange=e=>{settings.screenShake=e.target.checked;saveSettings()};$('#crosshairColor').value=settings.crosshairColor;$('#crosshairColor').oninput=e=>{settings.crosshairColor=e.target.value;saveSettings();applyCrosshair()};$('#centerDot').checked=settings.centerDot;$('#centerDot').onchange=e=>{settings.centerDot=e.target.checked;saveSettings();applyCrosshair()};
const presets={classic:{crosshairColor:'#f4f1ea',crosshairSize:12,crosshairThickness:2,crosshairGap:5,crosshairOpacity:100,centerDot:false},dot:{crosshairColor:'#ff7445',crosshairSize:2,crosshairThickness:2,crosshairGap:0,crosshairOpacity:100,centerDot:true},small:{crosshairColor:'#f4f1ea',crosshairSize:7,crosshairThickness:2,crosshairGap:3,crosshairOpacity:90,centerDot:false},cyan:{crosshairColor:'#65d9ff',crosshairSize:12,crosshairThickness:2,crosshairGap:5,crosshairOpacity:100,centerDot:false}};
$$('[data-preset]').forEach(b=>b.onclick=()=>{Object.assign(settings,presets[b.dataset.preset]);saveSettings();syncSettings();$$('.preset').forEach(x=>x.classList.toggle('active',x===b));});
function syncSettings(){['targetSize','targetSpeed','duration','sensitivity','crosshairSize','crosshairThickness','crosshairGap','crosshairOpacity'].forEach(id=>{const e=$('#'+id);e.value=settings[id];e.dispatchEvent(new Event('input'))});$('#crosshairColor').value=settings.crosshairColor;$('#centerDot').checked=settings.centerDot;$('#screenShake').checked=settings.screenShake;applyCrosshair()}
function applyCrosshair(){const c=$('#crosshair');if(!c)return;c.style.setProperty('--crosshair-color',settings.crosshairColor);c.style.setProperty('--ch-size',settings.crosshairSize+'px');c.style.setProperty('--ch-thickness',settings.crosshairThickness+'px');c.style.setProperty('--ch-gap',settings.crosshairGap+'px');c.style.setProperty('--crosshair-opacity',settings.crosshairOpacity/100);c.style.setProperty('--dot-size',settings.centerDot?'4px':'0px');$('#crosshairPreview').style.color=settings.crosshairColor;}
syncSettings();
$('#resetSettingsBtn').onclick=()=>{settings={...DEFAULTS};saveSettings();syncSettings()};
$('#resetStatsBtn').onclick=()=>{if(confirm('Reset all personal records?')){records={};saveRecords();updateStats();updateHome()}};
function updateHome(){const vals=Object.values(records);const best=Math.max(0,...vals.map(x=>x.score||0));const hits=vals.reduce((n,x)=>n+(x.hits||0),0),shots=vals.reduce((n,x)=>n+(x.shots||0),0),react=vals.filter(x=>x.avgReaction).map(x=>x.avgReaction);$('#homeBestScore').textContent=best;$('#homeAccuracy').textContent=shots?Math.round(hits/shots*100)+'%':'—';$('#homeBestReaction').textContent=react.length?Math.min(...react)+'ms':'—';$('#homeSessions').textContent=vals.length}
function updateStats(){const vals=Object.values(records),best=Math.max(0,...vals.map(x=>x.score||0)),hits=vals.reduce((n,x)=>n+(x.hits||0),0),shots=vals.reduce((n,x)=>n+(x.shots||0),0),react=vals.filter(x=>x.avgReaction).map(x=>x.avgReaction);$('#statsBestScore').textContent=best;$('#statsAccuracy').textContent=shots?Math.round(hits/shots*100)+'%':'—';$('#statsBestReaction').textContent=react.length?Math.min(...react)+' ms':'—';$('#statsHits').textContent=hits;$('#modeTable').innerHTML='<div class="table-head"><span>MODE</span><span>BEST SCORE</span><span>ACCURACY</span><span>BEST TIME</span></div>'+Object.entries(MODES).map(([id,m])=>{const r=records[id];return `<div><span>${m.name}</span><b>${r?.score||'—'}</b><span>${r?.shots?Math.round(r.hits/r.shots*100)+'%':'—'}</span><span>${r?.bestReaction?r.bestReaction+'ms':'—'}</span></div>`}).join('')}
function startGame(mode){currentMode=mode;const m=MODES[mode];$('#gameOverlay').hidden=false;$('#resultsModal').hidden=true;$('#gameMessage').hidden=false;$('#pausePanel').hidden=true;$('#gameMessageTitle').textContent=m.name;$('#beginBtn').textContent='Start drill  →';applyCrosshair();game={mode,m,active:false,paused:false,started:0,last:0,time:m.duration,hits:0,shots:0,score:0,reactions:[],target:null,targets:[],mouseX:innerWidth/2,mouseY:innerHeight/2};resizeCanvas();}
function closeGame(){cancelAnimationFrame(raf);$('#gameOverlay').hidden=true;game=null;}
$('#beginBtn').onclick=()=>{if(game&&!game.active){game.active=true;game.started=performance.now();game.last=game.started;$('#gameMessage').hidden=true;spawnTarget();raf=requestAnimationFrame(loop)}};
$('#pauseBtn').onclick=togglePause;$('#resumeBtn').onclick=togglePause;$('#exitBtn').onclick=()=>{closeGame();showScreen('home')};
function togglePause(){if(!game||!game.active)return;game.paused=!game.paused;$('#pausePanel').hidden=!game.paused;if(game.paused)cancelAnimationFrame(raf);else{game.last=performance.now();raf=requestAnimationFrame(loop)}}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&game?.active)togglePause();if(e.key.toLowerCase()==='f')$('#fullscreenBtn').click()});
const canvas=$('#gameCanvas'),ctx=canvas.getContext('2d');function resizeCanvas(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',()=>{if(game)resizeCanvas()});
function spawnTarget(){if(!game)return;const size=settings.targetSize*(game.mode==='precision'?.58:1),pad=Math.max(size+30,80);let x=pad+Math.random()*(innerWidth-pad*2),y=pad+Math.random()*(innerHeight-pad*2);game.target={x,y,size,created:performance.now(),vx:(Math.random()-.5)*settings.targetSpeed*230,vy:(Math.random()-.5)*settings.targetSpeed*180,life:0.75+Math.random()*1.2};}
function loop(now){if(!game||!game.active||game.paused)return;const dt=Math.min(.05,(now-game.last)/1000);game.last=now;game.time=Math.max(0,game.m.duration-(now-game.started)/1000);if(game.mode==='tracking'&&game.target){game.target.x+=game.target.vx*dt;game.target.y+=game.target.vy*dt;if(game.target.x<game.target.size||game.target.x>innerWidth-game.target.size)game.target.vx*=-1;if(game.target.y<game.target.size+60||game.target.y>innerHeight-game.target.size)game.target.vy*=-1}if(game.mode.type==='reaction'&&game.target&&now-game.target.created>game.target.life*1000){game.target=null;setTimeout(()=>{if(game?.active)spawnTarget()},300+Math.random()*1000)}draw(now);updateHud();if(game.time<=0||(game.m.goal&&game.hits>=game.m.goal)){finishGame();return}raf=requestAnimationFrame(loop)}
function draw(now){ctx.clearRect(0,0,innerWidth,innerHeight);ctx.fillStyle='#080b12';ctx.fillRect(0,0,innerWidth,innerHeight);ctx.strokeStyle='#ffffff08';ctx.lineWidth=1;for(let x=0;x<innerWidth;x+=80){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,innerHeight);ctx.stroke()}for(let y=0;y<innerHeight;y+=80){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(innerWidth,y);ctx.stroke()}if(!game.target)return;const t=game.target,p=t.size/2, pulse=1+Math.sin(now/180)*.04;ctx.save();ctx.translate(t.x,t.y);ctx.scale(pulse,pulse);ctx.beginPath();ctx.arc(0,0,p,0,Math.PI*2);ctx.fillStyle=game.mode.type==='reaction'?'#80e0ac':'#ff7445';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=20;ctx.fill();ctx.shadowBlur=0;ctx.beginPath();ctx.arc(0,0,p*.62,0,Math.PI*2);ctx.fillStyle='#111722';ctx.fill();ctx.beginPath();ctx.arc(0,0,p*.33,0,Math.PI*2);ctx.fillStyle=game.mode.type==='reaction'?'#80e0ac':'#ffb28e';ctx.fill();ctx.restore()}
function updateHud(){$('#hudScore').textContent=game.score;$('#hudHits').textContent=game.hits;$('#hudAccuracy').textContent=(game.shots?Math.round(game.hits/game.shots*100):100)+'%';$('#hudTime').textContent=Math.ceil(game.time)}
canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('mousedown',e=>{if(e.button!==2||!game?.active||game.paused)return;e.preventDefault();game.shots++;const t=game.target;if(t&&Math.hypot(e.clientX-t.x,e.clientY-t.y)<=t.size){game.hits++;const reaction=Math.round(performance.now()-t.created);game.reactions.push(reaction);game.score+=Math.max(50,Math.round(1000-reaction*.5));if(settings.screenShake){canvas.animate([{transform:'translate(2px,1px)'},{transform:'translate(-2px,-1px)'},{transform:'none'}],{duration:90})}spawnTarget()}else game.score=Math.max(0,game.score-25);updateHud()});
function finishGame(){if(!game)return;game.active=false;cancelAnimationFrame(raf);const avg=game.reactions.length?Math.round(game.reactions.reduce((a,b)=>a+b,0)/game.reactions.length):0,best=game.reactions.length?Math.min(...game.reactions):0,prev=records[currentMode];const isBest=!prev||game.score>(prev.score||0);records[currentMode]={score:Math.max(game.score,prev?.score||0),hits:Math.max(game.hits,prev?.hits||0),shots:game.shots,avgReaction:avg,bestReaction:Math.min(best||99999,prev?.bestReaction||99999)};saveRecords();$('#resultTitle').textContent=game.m.name;$('#resultScore').textContent=game.score;$('#resultAccuracy').textContent=(game.shots?Math.round(game.hits/game.shots*100):0)+'%';$('#resultHits').textContent=game.hits;$('#resultReaction').textContent=avg?avg+'ms':'—';$('#resultTps').textContent=(game.hits/Math.max(.1,game.m.duration-game.time)).toFixed(2);$('#newRecord').hidden=!isBest;$('#resultsModal').hidden=false;}
$('#againBtn').onclick=()=>startGame(currentMode);$('#resultHomeBtn').onclick=()=>{closeGame();showScreen('home')};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({settings,records},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='strafe-settings.json';a.click();URL.revokeObjectURL(a.href)};$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.settings)settings={...DEFAULTS,...d.settings};if(d.records)records=d.records;saveSettings();saveRecords();syncSettings();updateHome()}catch{alert('That file could not be imported.')}};r.readAsText(f)};
updateHome();
